<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Billet;
use AppBundle\Entity\Commande;

/**
 * billetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletsRepository extends \Doctrine\ORM\EntityRepository
{
    public function countBillets(Billet $billet)
    {
        return $this->createQueryBuilder('b')
            ->select('COUNT(b)')
            ->where('b.date = :date')
            ->setParameter('date', $billet->getDate())
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
