<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Commande;
use Symfony\Component\Validator\Constraints\DateTime;
use Doctrine\ORM\EntityRepository;


/**
 * commandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
    public function getCommandeWithBillet($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->innerJoin('c.billet', 'b')
            ->addSelect('b')
        ;

        $qb->where($qb->expr()->in('c.id', $id));

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function countBillets(Commande $commande)
    {
        return
            $this->createQueryBuilder('c')
                ->innerJoin('c.billets', 'b')
                ->select('COUNT(b)')
                ->andWhere('c.dateBillet = :date')
                ->setParameter('date', $commande->getDateBillet())
                ->getQuery()
                ->getSingleScalarResult()
        ;
    }

    public function sumBillet($idCommande)
    {
        $qb = $this->createQueryBuilder('c')
            ->innerJoin('c.billet', 'b')
            ->select('SUM(b.prix)')
            ->andWhere('b.commande = :idCommande')
            ->setParameter('idCommande', $idCommande)
            ->getQuery()
            ->getSingleScalarResult()
            ;
        return $qb;
    }

}
