<?php

namespace AppBundle\Repository;

/**
 * utilisateursAdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursAdressesRepository extends \Doctrine\ORM\EntityRepository
{
}
