<?php

namespace AppBundle\Repository\Service;

/**
 * JoursFeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoursFeriesRepository extends \Doctrine\ORM\EntityRepository
{
}
